- name: install Python 2.7 header files
  apt: pkg=python2.7-dev state=installed
  sudo: yes

- name: install numpy
  apt: pkg=python-numpy state=installed
  sudo: yes

- name: create build directory
  file: path={{ opencv_source_folder }}/build state=directory

- command: "cmake -D CMAKE_BUILD_TYPE=RELEASE \
	      -D CMAKE_INSTALL_PREFIX=/usr/local \
	      -D INSTALL_C_EXAMPLES=ON \
	      -D INSTALL_PYTHON_EXAMPLES=ON \
	      -D OPENCV_EXTRA_MODULES_PATH={{ opencv_contrib_folder }}/opencv_contrib/modules \
	      -D BUILD_EXAMPLES=ON .."
  args:
    chdir: "{{ opencv_source_folder}}/build"

- command: "make -j{{ raspberrypi_core_count }}"
  args:
    chdir: "{{ opencv_source_folder}}/build"

- command: "make install"
  sudo: yes
  args:
    chdir: "{{ opencv_source_folder}}/build"

- command: "ldconfig"
  sudo: yes
